# .readthedocs.yml
version: 2
sphinx:
  builder: html
  configuration: doc/conf.py
formats: all
build:
    image: latest
python:
  version: 3.6
  install:
    - requirements: doc/requirements.txt
    - method: pip
      path: .
  system_packages: true