trigger:
  branches:
    include:
      - master
      - development
  tags:
    include:
    - v*

pr:
  branches:
    include:
    - '*'

stages:
- stage: Build
  jobs:
  # QA
  - job: lint
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - template: ci/lint.yml

  # Build
  # Linux
  # TODO: Turn off Linux Testing until https://github.com/sdispater/poetry/issues/1197 is resolved
  - job: test_linux
    dependsOn: lint
    pool:
      vmImage: 'ubuntu-16.04'
    strategy:
      matrix:
        Python36:
          python.version: '3.6'
    steps:
    - bash: |
        sudo apt update
        sudo apt install swig3.0
        sudo ln -s /usr/bin/swig3.0 /usr/bin/swig
      displayName: Install swig on Linux
    - template: ci/install.yml
    - template: ci/tests.yml

  #MacOS
  # # MacOs builds seem to be hanging
  # - job: test_macos
  #   dependsOn: lint
  #   pool:
  #     vmImage: 'macOS-10.13'
  #   strategy:
  #     matrix:
  #       Python36:
  #         python.version: '3.6'
  #   steps:
  #   - script: |
  #       brew install swig
  #       brew install gcc@5
  #     displayName: Install Brew packages
  #   - template: ci/install.yml
  #   - template: ci/tests.yml

# TODO: switch to linux box release when the above is fixed
# - stage: Release
#   condition: contains(variables['Build.SourceBranch'], 'tags')
#   jobs:
#   - job: release
#     pool:
#       vmImage: 'macOS-10.13'
#     steps:
#     - task: UsePythonVersion@0
#       inputs:
#         versionSpec: '3.6'
#       displayName: Select Python version
#     - script: |
#         brew install swig
#         brew install gcc@5
#       displayName: Install Brew packages
#     - template: ci/install.yml
#     - script: poetry build
#         poetry publish -u $(pypi_username) -p $(pypi_password)
#       displayName: Release to pypi
#     - task: GitHubRelease@0
#       inputs:
#         gitHubConnection: georgianpartners
#         repositoryName: georgianpartners/foreshadow
#         tagSource: 'auto'
#         assets:
#           dist/*
#       displayName: Add release to GitHub